image: ubuntu:latest

before_script:

  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  - eval $(ssh-agent -s)

  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  
deploy:
  script:
    # Deploy
    - ssh -o StrictHostKeyChecking=no rospatent@rospatent-back.msharks.ru "cd /var/www/frontend; git pull && yarn && yarn build"
  only:
    - master